name: flutter_form_bloc
description: Flutter widgets that make it easy to create forms with form_bloc.
version: 0.0.1
author: GiancarloCode <GiancarloCode@gmail.com>
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository:  https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker:  https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  form_bloc: ^0.1.1
  flutter_bloc: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
