name: flutter_form_bloc
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State. 
version: 0.4.1+1
author: GiancarloCode <GiancarloCode@gmail.com>
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.15.0
  form_bloc: ^0.5.0
  flutter_bloc: ^0.21.0
  rxdart: ^0.22.1+1
  keyboard_visibility: ^0.5.1 
  collection: ^1.14.11

dev_dependencies:
  flutter_test: 
    sdk: flutter
  pedantic: ^1.7.0
