name: form_bloc
description: A simple way to create forms with bloc.
version: 0.1.1
author: GiancarloCode <GiancarloCode@gmail.com>
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
repository:  https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
issue_tracker:  https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  bloc: ^0.14.4
  rxdart: ^0.22.1
  equatable: ^0.4.0
  meta: ^1.1.6

dev_dependencies:
  test: ^1.6.0
