name: flutter_form_bloc_example
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  flutter_form_bloc:
    path: ../
  form_bloc: ^0.2.0
  flutter_bloc: ^0.20.1
  shared_preferences: ^0.5.3+4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
